name: pygtkwin environment
description: |
  Initializes pygtkwin environment
inputs:
  arch:
    description: MSVC target architecture (x86 or x64)
    required: true
runs:
  using: composite
  steps:
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
      with:
        arch: ${{ inputs.arch }}

    - name: Configure pygtkwin environment
      shell: pwsh
      run: |
        & "$env:GITHUB_ACTION_PATH/configure.ps1"
