name: pygtkwin environment
description: |
  Initializes pygtkwin environment
runs:
  using: composite
  steps:
    - name: Configure pygtkwin environment
      shell: pwsh
      run: |
        & "$env:GITHUB_ACTION_PATH/configure.ps1"
